# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


def fibonacci(max_number):
    first = 0
    second = 1
    yield 1

    while second < max_number:
        yield second
        third = first + second
        first = second
        second = third


def even_fibonacci(max_number):
    for x in fibonacci(max_number):
        if x % 2 == 0:
            yield x


sum = 0

for x in even_fibonacci(4_000_000):
    sum += x

print("Sum is ", sum)
